exec(open("pre_process.py").read())
print("pre_process Done")
exec(open("drop_duplicates.py").read())
print("drop_duplicates Done")
exec(open("create_dir.py").read())
exec(open("5-folds.py").read())
print("5-folds Done")
exec(open("discretize.py").read())
print("discretize Done")
exec(open("encode_categorical.py").read())
print("encode_categorical Done")
exec(open("undersampling.py").read())
print("undersampling Done")
exec(open("ML_algorithms.py").read())
exec(open("ML_algorithms_unknown.py").read())
