# print("join_web_attack...")
# exec(open("join_web_attack.py").read())
# print("pre_process...")
# exec(open("pre_process.py").read())
exec(open("create_dir.py").read())
# print("5-folds...")
# exec(open("5-folds.py").read())
# print("undersampling...")
# exec(open("undersampling.py").read())
print("normalize...")
exec(open("normalize.py").read())
print("discretize...")
exec(open("discretize.py").read())
print("encode_categorical...")
exec(open("encode_categorical.py").read())
print("ML_algorithms...")
exec(open("ML_algorithms.py").read())
print("ML_algorithms_unknown...")
exec(open("ML_algorithms_unknown.py").read())
print("colect_results...")
exec(open("colect_results.py").read())
